#!/usr/bin/env groovy

@Library('jenkins-shared-libs')
import static com.ericsson.orchestration.mgmt.libs.VnfmJenkins.getAgentLabel
import static com.ericsson.orchestration.mgmt.libs.VnfmJenkins.getSeedJobName


// Stages template
def stages = [:]
// Set Agent label
String label = getAgentLabel( type: 'concurrent',
                              this)


node(label) {
    try {
        // Set Job's ENVs
        env.SEED_JOB = getSeedJobName(JOB_NAME)
        env.JOB_TYPE = 'helmfile-release'
        env.GLOBAL_VAR_PATH = 'jenkins/global.var'
        env.VAR_PATH = 'jenkins/' + env.SEED_JOB + '/project.var'
        env.APP_NAME = params.APP_NAME
        env.CHART_NAME = params.CHART_NAME
        env.CHART_REPO = params.CHART_REPO
        env.CHART_VERSION = params.CHART_VERSION
        env.GERRIT_REFSPEC = params.GERRIT_REFSPEC
        env.EVNFM_BRANCH = params.EVNFM_BRANCH


        // Run Prepare Stage
        stage('Prepare') {
            println('INFO: Checkout CI code...')
            checkout(scm)

            println('INFO: Load Global vars...')
            load(env.GLOBAL_VAR_PATH)

            println('INFO: Load Project vars...')
            load(env.VAR_PATH)

            println('INFO: Load Stages...')
            stages['envs'] = load(env.ENVS_STAGE)
            stages['run-job'] = load(env.RUN_JOB_STAGE)
            stages['post'] = load(env.POST_STAGE)
        }

        // Run Update ENVs Stage
        stages['envs'].RunUpdateEVNFM(env.INTEGRATION_CI_PROJECT,
                                      env.RESOURCE_NAME)

        // Run Job ADP_CHART_RELEASE
        stages['run-job'].RemoteJob(name: (env.ADP_CHART_RELEASE).split(':')[1],
                                    server: (env.ADP_CHART_RELEASE).split(':')[0],
                                    params: env.ADP_CHART_RELEASE_PARAMS,
                                    artifact: 'artifact.properties',
                                    stage: 'Helmfile Release')

    } catch (Exception errJob) {
        println(errJob)
        currentBuild.result = 'FAILURE'
    } finally {
        // Run Post Actions stage
        stages['post'].Helmfile()
    }
}