#!/usr/bin/env groovy

@Library('jenkins-shared-libs')
import static com.ericsson.orchestration.mgmt.libs.VnfmJenkins.getAgentLabel
import static com.ericsson.orchestration.mgmt.libs.VnfmJenkins.getSeedJobName
import static com.ericsson.orchestration.mgmt.libs.VnfmGerrit.getLatestTag


// Stages template
def stages = [:]
// Label of the runner
env.SEED_JOB = getSeedJobName(JOB_NAME)
String label = getAgentLabel( type: 'post-merge',
                              project: env.SEED_JOB,
                              this)


node(label) {
    try {
        // Set Job's ENVs
        env.JOB_TYPE = 'post-merge'
        env.GLOBAL_VAR_PATH = 'jenkins/global.var'
        env.VAR_PATH = 'jenkins/' + env.SEED_JOB + '/project.var'
        env.GERRIT_BRANCH = 'master'


        // Run Prepare Stage
        stage('Prepare') {
            println('INFO: Checkout CI code...')
            checkout(scm)

            println('INFO: Load Global vars...')
            load(env.GLOBAL_VAR_PATH)

            println('INFO: Load Project vars...')
            load(env.VAR_PATH)

            println('INFO: Load Stages...')
            stages['git'] = load(env.GIT_STAGE)
            stages['envs'] = load(env.ENVS_STAGE)
            stages['quality-tests'] = load(env.QUALITY_TESTS_STAGE)
            stages['sonar'] = load(env.SONAR_STAGE)
            stages['helm'] = load(env.HELM_STAGE)
            stages['clean'] = load(env.CLEAN_STAGE)

            env.PROJECT_TAG = getLatestTag( project: env.GERRIT_PROJECT,
                                            url: env.GERRIT_URL,
                                            this)
            println('INFO: Latest tag is ' + env.PROJECT_TAG)
        }

        // Run Checkout Project Stage
        stages['git'].CheckoutProject(project: env.GERRIT_PROJECT,
                                      branch: env.GERRIT_BRANCH,
                                      type: 'tag',
                                      tag: env.PROJECT_TAG)

        // Run Update Job ENVs Stage
        stages['envs'].Update(project: env.GERRIT_PROJECT,
                              pom: env.POM_FILE)

        // Run Coverage Test Stage
        stages['quality-tests'].CoverageTest(project: env.GERRIT_PROJECT)

        // Run Sonar Analysis Stage
        stages['sonar'].Analysis( project: env.GERRIT_PROJECT,
                                  pom: env.POM_FILE,
                                  abort: false)

        // Run Package Helm Chart Stage
        stages['helm'].PackageChart(project: env.GERRIT_PROJECT,
                                    folder: env.CHART_FOLDER,
                                    upload: false)

        // Run Design Rule Check Stage
        stages['helm'].DesignRuleCheck( project: env.GERRIT_PROJECT,
                                        upload: true)

    } catch (Exception errJob) {
        println(errJob)
        currentBuild.result = 'FAILURE'
    } finally {
        // Run Clean Stage
        stages['clean'].CleanBuild()
    }
}