#!/usr/bin/env groovy

@Library('jenkins-shared-libs')
import static Boolean.parseBoolean
import static com.ericsson.orchestration.mgmt.libs.VnfmJenkins.getAgentLabel
import static com.ericsson.orchestration.mgmt.libs.VnfmJenkins.getSeedJobName


// Stages template
def stages = [:]
// Set Agent label
env.SEED_JOB = getSeedJobName(JOB_NAME)
String label = getAgentLabel( type: 'unit-tests',
                              project: env.SEED_JOB,
                              topic: env.GERRIT_TOPIC,
                              this)


node(label) {
    try {
        // Set Job's ENVs
        env.JOB_TYPE = 'gerrit'
        env.GLOBAL_VAR_PATH = 'jenkins/global.var'
        env.VAR_PATH = 'jenkins/' + env.SEED_JOB + '/project.var'
        env.GERRIT_BRANCH = params.GERRIT_BRANCH ?: 'master'
        env.GERRIT_REFSPEC = params.GERRIT_REFSPEC ?: 'refs/heads/master'


        // Run Prepare Stage
        stage('Prepare') {
            println('INFO: Checkout CI code...')
            checkout(scm)

            println('INFO: Load Global vars...')
            load(env.GLOBAL_VAR_PATH)

            println('INFO: Load Project vars...')
            load(env.VAR_PATH)

            println('INFO: Load Stages...')
            stages['git'] = load(env.GIT_STAGE)
            stages['envs'] = load(env.ENVS_STAGE)
            stages['build'] = load(env.BUILD_STAGE)
            stages['unit-tests'] = load(env.UNIT_TESTS_STAGE)
            stages['clean'] = load(env.CLEAN_STAGE)
            if(!parseBoolean(env.SKIP_BUILD_IMAGE_TEST)) {
                stages['docker'] = load(env.DOCKER_STAGE)
            }
        }

        // Run Checkout Project Stage
        stages['git'].CheckoutProject(project: env.GERRIT_PROJECT,
                                      branch: env.GERRIT_BRANCH,
                                      refspec: env.GERRIT_REFSPEC,
                                      type: 'change')

        // Run Update Job ENVs Stage
        stages['envs'].Update(project: env.GERRIT_PROJECT,
                              pom: env.POM_FILE)

        // Run Build Stage
        stages['build'].BuildMaven( project: env.GERRIT_PROJECT,
                                    pom: env.POM_FILE)

        // Run Unit Tests Stage
        stages['unit-tests'].MavenUnitTests(project: env.GERRIT_PROJECT,
                                            pom: env.POM_FILE)

        if(!parseBoolean(env.SKIP_E2E_TESTS)) {
            // Run End-to-End Tests Stage
            stages['unit-tests'].MavenE2ETests(project: env.GERRIT_PROJECT)
        }

        if(!parseBoolean(env.SKIP_BUILD_IMAGE_TEST)) {
            // Run Build Image Stage
            stages['docker'].BuildImage(name: env.GERRIT_PROJECT)
        }

    } catch (Exception errJob) {
        println(errJob)
        currentBuild.result = 'FAILURE'
    } finally {
        // Run Clean Stage
        stages['clean'].CleanBuild()
    }
}