#!/usr/bin/env groovy

@Library('jenkins-shared-libs')
import static com.ericsson.orchestration.mgmt.libs.VnfmJenkins.getAgentLabel


// Stages template
def stages = [:]
// Set Agent label
String label = getAgentLabel( type: 'gerrit',
                              this)


node(label) {
    try {
        // Set Job's ENVs
        env.GLOBAL_VAR_PATH = 'jenkins/global.var'
        env.TYPE = params.TYPE
        env.DNS_NAME = params.DNS_NAME


        // Run Prepare Stage
        stage('Prepare') {
            println('INFO: Checkout CI code...')
            checkout(scm)

            println('INFO: Load Global vars...')
            load(env.GLOBAL_VAR_PATH)

            println('INFO: Load Stages...')
            stages['envs'] = load(env.ENVS_STAGE)
            stages['deploy-app'] = load(env.DEPLOY_APP_STAGE)
            stages['clean'] = load(env.CLEAN_STAGE)
        }

        // Run Update Job ENVs Stage
        stages['envs'].UpdateHelmfile()

        // Run Genarate SSL Certificates Stage
        stages['deploy-app'].GenerateSSL(name: env.DNS_NAME,
                                         type: env.TYPE)

    } catch (Exception errJob) {
        println(errJob)
        currentBuild.result = 'FAILURE'
    } finally {
        // Run Clean Stage
        stages['clean'].CleanBuild()
    }
}