#!/usr/bin/env groovy

@Library('jenkins-shared-libs')
import static com.ericsson.orchestration.mgmt.libs.VnfmJenkins.getAgentLabel
import static com.ericsson.orchestration.mgmt.libs.VnfmJenkins.getSeedJobName


// Stages template
def stages = [:]
// Set Agent label
String label = getAgentLabel( type: 'deploy',
                              topic: params.GERRIT_TOPIC,
                              this)


node(label) {
    try {
        // Set Job's ENVs
        env.SEED_JOB = getSeedJobName(JOB_NAME)
        env.JOB_TYPE = 'gerrit'
        env.GLOBAL_VAR_PATH = 'jenkins/global.var'
        env.VAR_PATH = 'jenkins/' + env.SEED_JOB + '/project.var'
        env.GERRIT_BRANCH = env.GERRIT_BRANCH ?: 'master'
        env.GERRIT_REFSPEC = env.GERRIT_REFSPEC ?: 'refs/heads/master'


        // Run Prepare Stage
        stage('Prepare') {
            println('INFO: Checkout CI code...')
            checkout(scm)

            println('INFO: Load Global vars...')
            load(env.GLOBAL_VAR_PATH)

            println('INFO: Load Project vars...')
            load(env.VAR_PATH)

            println('INFO: Load Stages...')
            stages['git'] = load(env.GIT_STAGE)
            stages['envs'] = load(env.ENVS_STAGE)
            stages['docker'] = load(env.DOCKER_STAGE)
            stages['build'] = load(env.BUILD_STAGE)
            stages['helm'] = load(env.HELM_STAGE)
            stages['deploy-app'] = load(env.DEPLOY_APP_STAGE)
            stages['ua-tests'] = load(env.UA_TESTS_STAGE)
            stages['post'] = load(env.POST_STAGE)
            stages['clean'] = load(env.CLEAN_STAGE)
        }

        // Run Checkout Project Stage
        stages['git'].CheckoutProject(project: env.GERRIT_PROJECT,
                                      branch: env.GERRIT_BRANCH,
                                      refspec: env.GERRIT_REFSPEC,
                                      type: 'change')

        // Run Update Job ENVs Stage
        stages['envs'].Update(project: env.GERRIT_PROJECT)

        // Run Build Image Stage
        stages['docker'].BuildImage(name: env.GERRIT_PROJECT)
        env.UPDATE_SOURCE = env.IMAGE_NAME
        env.HELM_EXECUTOR_VERSION = env.IMAGE_VERSION
        env.HELM_EXECUTOR_REPO = env.IMAGE_REPO.minus(env.IMAGE_REPO.split('proj-am')[0])
        currentBuild.description = "<p>${env.IMAGE_NAME}: ${env.HELM_EXECUTOR_VERSION}</p>"

        // Run Checkout Project Stage for WFS
        env.DISABLE_SUBMODULES = false
        stages['git'].CheckoutProject(project: env.WFS_GERRIT_PROJECT,
                                      branch: env.WFS_GERRIT_BRANCH)

        // Run Update Job ENVs Stage for WFS
        stages['envs'].Update(project: env.WFS_GERRIT_PROJECT,
                              stage: 'Update Job ENVs for WFS')

        // Run Build Stage for WFS
        stages['build'].BuildMaven( project: env.WFS_GERRIT_PROJECT,
                                    stage: 'Build WFS')

        // Run Build WFS Image Stage
        stages['docker'].BuildImage(name: env.WFS_GERRIT_PROJECT,
                                    stage: 'Build WFS Image')

        // Run Package WFS Chart Stage
        stages['helm'].PackageChart(project: env.WFS_GERRIT_PROJECT,
                                    chart: env.WFS_CHART_NAME,
                                    stage: 'Package WFS Chart')

        // Run Package WFS Dependency Chart Stage
        stages['helm'].PackageDependency( project: env.WFS_GERRIT_PROJECT,
                                          chart: env.WFS_CHART_NAME,
                                          stage: 'Package WFS Dependency Chart')

        // Run Update Helm Chart Stage
        stages['helm'].UpdateHelmChart(name: env.WFS_GERRIT_PROJECT)

        // Run Prepare Deploy Stage
        stages['deploy-app'].Prepare(project: env.GERRIT_PROJECT)

        // Run Deploy Dependency Stage
        stages['deploy-app'].DeployDependency(name: env.WFS_GERRIT_PROJECT,
                                              chart: env.WFS_CHART_NAME)

        // Run Deploy Stage
        stages['deploy-app'].Deploy(name: env.WFS_GERRIT_PROJECT,
                                    chart: env.WFS_CHART_NAME)

        // Run Acceptance Tests Stage
        stages['ua-tests'].MavenTests(name: env.WFS_GERRIT_PROJECT)

    } catch (Exception errJob) {
        println(errJob)
        currentBuild.result = 'FAILURE'
    } finally {
        // Run Post Actions Stage
        stages['post'].GerritDeploy(status: currentBuild.result ?: 'SUCCESS')

        // Run Clean Stage
        stages['clean'].CleanBuild(deleteDeploy: true)
    }
}