#!/usr/bin/env groovy

@Library('jenkins-shared-libs')
import static com.ericsson.orchestration.mgmt.libs.VnfmJenkins.getAgentLabel
import static com.ericsson.orchestration.mgmt.libs.VnfmJenkins.getSeedJobName
import static com.ericsson.orchestration.mgmt.libs.VnfmGerrit.getLatestTag


// Stages template
def stages = [:]
// Set Agent label
String label = getAgentLabel( type: 'post-merge',
                              topic: params.GERRIT_TOPIC,
                              this)


node(label) {
    try {
        // Set Job's ENVs
        env.SEED_JOB = getSeedJobName(JOB_NAME)
        env.JOB_TYPE = 'post-merge'
        env.GLOBAL_VAR_PATH = 'jenkins/global.var'
        env.VAR_PATH = 'jenkins/' + env.SEED_JOB + '/project.var'
        env.GERRIT_BRANCH = 'master'


        // Run Prepare Stage
        stage('Prepare') {
            println('INFO: Checkout CI code...')
            checkout(scm)

            println('INFO: Load Global vars...')
            load(env.GLOBAL_VAR_PATH)

            println('INFO: Load Project vars...')
            load(env.VAR_PATH)

            println('INFO: Load Stages...')
            stages['git'] = load(env.GIT_STAGE)
            stages['envs'] = load(env.ENVS_STAGE)
            stages['run-job'] = load(env.RUN_JOB_STAGE)
            stages['quality-tests'] = load(env.QUALITY_TESTS_STAGE)
            stages['sonar'] = load(env.SONAR_STAGE)
            stages['clean'] = load(env.CLEAN_STAGE)

            env.PROJECT_TAG = getLatestTag( project: env.GERRIT_PROJECT,
                                            url: env.GERRIT_URL,
                                            this)
            println('INFO: Latest tag is ' + env.PROJECT_TAG)
        }

        // Run Checkout Project Stage
        stages['git'].CheckoutProject(project: env.GERRIT_PROJECT,
                                      branch: env.GERRIT_BRANCH,
                                      type: 'tag',
                                      tag: env.PROJECT_TAG)

        // Run Update Job ENVs Stage
        stages['envs'].Update(project: env.GERRIT_PROJECT)

        // Run Uplift Child Chart Job
        ArrayList upliftJobParams = []
        upliftJobParams.add(name: 'CHART_NAME',
                            value: env.CHART_NAME)
        upliftJobParams.add(name: 'CHART_VERSION',
                            value: env.CHART_VERSION)
        upliftJobParams.add(name: 'UMBRELLA_PROJECT_NAME',
                            value: env.WFS_GERRIT_PROJECT)
        upliftJobParams.add(name: 'UMBRELLA_PROJECT_BRANCH',
                            value: env.WFS_GERRIT_BRANCH)
        upliftJobParams.add(name: 'UMBRELLA_CHART_FILE',
                            value: env.WFS_UPDATING_FILE)
        stages['run-job'].LocalJob( name: env.UPLIFT_CHILD_CHART_JOB,
                                    params: upliftJobParams)

        // Run Coverage Test Stage
        stages['quality-tests'].CoverageTest(project: env.GERRIT_PROJECT)

        // Run Sonar Analysis Stage
        stages['sonar'].Analysis( project: env.GERRIT_PROJECT,
                                  pom: env.POM_FILE)

    } catch (Exception errJob) {
        println(errJob)
        currentBuild.result = 'FAILURE'
    } finally {
        // Run Clean Stage
        stages['clean'].CleanBuild()
    }
}