galaxy_info:
  role_name: common-ca
  description: Populate common CA between Jenkins nodes and K8S nodes
  min_ansible_version: 2.4
  platforms:
    - name: EL
      versions:
        - 7
        - 8