- name: "Check Kubectl"
  shell: "kubectl version --client"
  register: kubectl_check
  ignore_errors: true
  changed_when: false

- name: "Install Kubectl"
  get_url:
    url: "{{ kubectl_url }}"
    dest: "/usr/bin/kubectl"
    mode: "0555"
    force: true
  when: kubectl_check.stdout == ""

- name: "Kubectl status"
  debug:
    msg: "kubectl version: {{ kubectl_check.stdout }}"
  when: kubectl_check.stdout